-- Fix UTF-8 encoding for products table
ALTER TABLE `products` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `categories` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Update products with correct UTF-8 encoding
UPDATE `products` SET `name` = 'Khóa vân tay GATEMAN FINGUS (WF-20)' WHERE `id` = 1;
UPDATE `products` SET `name` = 'Khóa vân tay Samsung SHP-DH538' WHERE `id` = 2;
UPDATE `products` SET `name` = 'Khóa vân tay SamSung SHS P718' WHERE `id` = 3;
UPDATE `products` SET `name` = 'Khóa SAMSUNG SHS-2920' WHERE `id` = 4;
UPDATE `products` SET `name` = 'Khóa điện tử SAMSUNG SHP-DS700' WHERE `id` = 5;
UPDATE `products` SET `name` = 'Khóa điện tử SAMSUNG SHS 1321' WHERE `id` = 6;
UPDATE `products` SET `name` = 'Khóa vân tay SAMSUNG SHP-DP930' WHERE `id` = 7;
UPDATE `products` SET `name` = 'Khóa vân tay Samsung SHS-H700' WHERE `id` = 8;
UPDATE `products` SET `name` = 'Chuông cửa hình SAMSUNG SHT-3517NT' WHERE `id` = 9;
UPDATE `products` SET `name` = 'SamSung SHS G510: Khóa cửa kính' WHERE `id` = 10;
UPDATE `products` SET `name` = 'Khóa điện tử GATEMAN WG-200' WHERE `id` = 11;
UPDATE `products` SET `name` = 'Khóa vân tay GATEMAN WF200' WHERE `id` = 12;
UPDATE `products` SET `name` = 'Khóa vân tay GATEMAN Z10-IH' WHERE `id` = 13;
UPDATE `products` SET `name` = 'GATEMAN F300-FH' WHERE `id` = 14;
UPDATE `products` SET `name` = 'Khóa vân tay GATEMAN F50-FH' WHERE `id` = 15;
UPDATE `products` SET `name` = 'Khóa vân tay H-Gang TR812' WHERE `id` = 16;
UPDATE `products` SET `name` = 'Khóa cửa kính H-Gang Sync TG330' WHERE `id` = 17;
UPDATE `products` SET `name` = 'Khóa điện tử H-Gang TR100' WHERE `id` = 18;
UPDATE `products` SET `name` = 'Khóa vân tay H-Gang TM902-KV' WHERE `id` = 19;
UPDATE `products` SET `name` = 'Khóa điện tử H-Gang Sync TM700' WHERE `id` = 20;
UPDATE `products` SET `name` = 'Khóa điện tử H-Gang Sync TR700' WHERE `id` = 21;
UPDATE `products` SET `name` = 'Khóa điện tử H-Gang Sync TS700' WHERE `id` = 22;
UPDATE `products` SET `name` = 'Khóa vân tay H-Gang TM901' WHERE `id` = 23;
UPDATE `products` SET `name` = 'Khóa vân tay EPIC ES-F700G' WHERE `id` = 24;
UPDATE `products` SET `name` = 'Khóa vân tay EPIC ES F300D' WHERE `id` = 25;
UPDATE `products` SET `name` = 'EPIC 100D' WHERE `id` = 26;
UPDATE `products` SET `name` = 'Khóa vân tay EPIC EF-8000L' WHERE `id` = 27;
UPDATE `products` SET `name` = 'EPIC ES-303 GR: Khóa cửa kính' WHERE `id` = 28;
UPDATE `products` SET `name` = 'EPIC POPScan M' WHERE `id` = 29;
UPDATE `products` SET `name` = 'EPIC ES 303 G: Khóa cửa kính' WHERE `id` = 30;
UPDATE `products` SET `name` = 'Khóa điện tử EPIC N-Touch' WHERE `id` = 31;
UPDATE `products` SET `name` = 'EPIC 809 L/LR' WHERE `id` = 32;
UPDATE `products` SET `name` = 'Khóa WELKOM WAT 310' WHERE `id` = 33;
UPDATE `products` SET `name` = 'WELKOM WSP-2500B' WHERE `id` = 34;
UPDATE `products` SET `name` = 'WELKOM WGT330' WHERE `id` = 35;
UPDATE `products` SET `name` = 'WELKOM WRT300' WHERE `id` = 36;
UPDATE `products` SET `name` = 'Khóa vân tay KAISER+ M-1190S' WHERE `id` = 37;
UPDATE `products` SET `name` = 'Khóa vân tay KAISER+ 7090' WHERE `id` = 38;
UPDATE `products` SET `name` = 'Khóa vân tay cửa kính KAISER+ HG-1390' WHERE `id` = 39;
UPDATE `products` SET `name` = 'Khóa vân tay UNICOR UN-7200B' WHERE `id` = 40;
UPDATE `products` SET `name` = 'Khóa điện tử Unicor ZEUS 6700sk' WHERE `id` = 41;
UPDATE `products` SET `name` = 'Khóa điện tử HiOne+ M-1100S' WHERE `id` = 42;
UPDATE `products` SET `name` = 'Khóa điện tử HiOne+ H-3400SK' WHERE `id` = 43;
UPDATE `products` SET `name` = 'Khóa vân tay HiOne+ H-5490SK' WHERE `id` = 44;
UPDATE `products` SET `name` = 'Bộ chuông cửa có hình KOCOM KCV-434 + KC-C60' WHERE `id` = 45;
UPDATE `products` SET `name` = 'Khóa cửa kính TANK GT330' WHERE `id` = 46;
UPDATE `products` SET `name` = 'Khóa cửa kính Sync Auto 2-way TG310' WHERE `id` = 47;
